Models/ErrorViewModel.cs
using System;

namespace PDFUpload.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/FileUploadController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Text;
using Microsoft.AspNetCore.StaticFiles;
using iTextSharp.text.pdf;
using System.Text.RegularExpressions;

namespace PDFUpload.Controllers
{
    public class FileUploadController : Controller
    {
        private readonly string wwwrootDirectory =
            Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/UploadedPdfs");

        //public IActionResult Index()
        //{
        //    Console.WriteLine("From Index");
        //    System.Diagnostics.Debug.WriteLine("Index");
        //    return View();
        //}

        [HttpPost]
        public async Task<IActionResult> Index(IFormFile uploadedFile)
        {
            ViewData.Clear();
            //To Create directory if directory is not found
            if (!Directory.Exists(wwwrootDirectory))
            {
                Directory.CreateDirectory(wwwrootDirectory);
            }

            if (uploadedFile == null)
            {
                ViewBag.Message = "Choose File to upload";
                // to get msg in console
                System.Diagnostics.Debug.WriteLine("File need to upload");
            }
            else
            {
                var checkThisPath = wwwrootDirectory + "/" + uploadedFile.FileName;
                FileInfo file = new FileInfo(checkThisPath);
                System.Diagnostics.Debug.WriteLine("Check File Existes: " + file.Exists);

                if (!file.Exists)
                {
                    //To check the file extention
                    if (Path.GetExtension(uploadedFile.FileName) == ".pdf")
                    {

                        // To get msg in console for validating file type
                        System.Diagnostics.Debug.WriteLine("File extention is " + (Path.GetExtension(uploadedFile.FileName) == ".pdf"));

                        //To check file type (Just for ref)
                        string s = checkFileType(uploadedFile);
                        var path = Path.Combine(
                            wwwrootDirectory,
                            //uploadedFile.FileName + Path.GetExtension(uploadedFile.FileName) // Save file name+extention
                            uploadedFile.FileName //Save only file name
                            );

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await uploadedFile.CopyToAsync(stream);
                        }

                        ViewBag.Message = uploadedFile.FileName + " Uploaded " + s;

                        //return console
                        System.Diagnostics.Debug.WriteLine("Uploaded");
                        //TO valid PDF
                        try
                        {
                            checkPages(uploadedFile);
                        }
                        catch (Exception e)
                        {
                            System.Diagnostics.Debug.WriteLine(e);
                            System.Diagnostics.Debug.WriteLine("Not a Valid PDF");
                            string checkError = e + "";
                            if (checkError.Contains("InvalidPdfException"))
                            {
                                ViewBag.Message = "Not A valid PDF. Try Valid PDF";
                                file.Delete();

                            }
                        }
                    }
                    else
                    {
                        ViewBag.Message = "allowed only pdf but given file is " + Path.GetExtension(uploadedFile.FileName);
                        // To get console message
                        System.Diagnostics.Debug.WriteLine("Uploaded file is " + Path.GetExtension(uploadedFile.FileName) + " Not Allowed");
                    }
                }
                else
                {
                    ViewBag.Message = "File alredy Exists. Try another one.";
                    System.Diagnostics.Debug.WriteLine("File already Present");
                }
            }

            return View("Views/Home/Index.cshtml");
        }

        //To verify the uploaded file is pdf or not by readinng the pages
        private void checkPages(IFormFile uploadedFile)
        {

            string pdfPath = wwwrootDirectory + "/" + uploadedFile.FileName;
            PdfReader pdfReader = new PdfReader(pdfPath);
            int numberOfPages = pdfReader.NumberOfPages;
            System.Diagnostics.Debug.WriteLine(numberOfPages);

        }

        // returns file content type
        private string checkFileType(IFormFile FileName)
        {
            string contentType;
            new FileExtensionContentTypeProvider().TryGetContentType(FileName.FileName, out contentType);
            // return contentType ?? "application/octet-stream";
            return contentType;
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PDFUpload.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PDFUpload.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/FileUpload/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*<div class="container">
    @using (Html.BeginForm("Index", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            <div class="form-group">
                <input type="file" class="form-control" name="uploadedFile" accept="application/pdf,application/vnd.ms-excel" />
            </div>
            <div class="form-group">
                <input type="submit" name="fileUpload" value="Upload" />
                @ViewBag.Message
            </div>
        </div>

    }
</div>*@

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <div class="container">
        @using (Html.BeginForm("Index", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div>
                <div class="form-group">
                    <input type="file" class="input-group-text" name="uploadedFile" onchange="" accept="application/pdf,application/vnd.ms-excel" />
                </div>
                <div class="form-group">
                    <input type="submit" name="fileUpload" value="Upload" />
                    @*@ViewBag.Message*@
                    <span class="styleCalss" id="v"></span>
                </div>
            </div>

        }
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        //alert("@ViewBag.Message");
        var v = "@ViewBag.Message";
        document.getElementById("v").innerHTML = v;

        if (v.includes("Uploaded")) {
            document.getElementById("v").className = "success";
        } else {
            document.getElementById("v").className = "danger";
        }


    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PDFUpload</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PDFUpload</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileUpload" asp-action="Index">Upload File</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PDFUpload - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>